# Generated by Django 5.2.7 on 2025-11-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_image_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_src',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
