# Generated by Django 5.2.7 on 2025-11-07 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_product_image_src_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockcategory', models.CharField(max_length=20)),
                ('Icon_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='productcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockcategory'),
        ),
    ]
