# Generated by Django 5.2.7 on 2025-10-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcard',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard_icons/'),
        ),
    ]
