# Generated by Django 5.2.7 on 2025-10-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_dashboardcard_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dashboard_card',
            new_name='category',
        ),
    ]
