# Generated by Django 5.2.7 on 2025-10-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_category_product_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
