# Generated by Django 5.2.7 on 2025-10-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
