# Generated by Django 5.2.7 on 2025-10-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
