# Generated by Django 5.2.7 on 2025-11-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockcategory_alter_product_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcategory',
            name='Icon_img',
        ),
        migrations.AlterField(
            model_name='stockcategory',
            name='stockcategory',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcategory', models.CharField(max_length=50)),
                ('ico_img', models.ImageField(blank=True, null=True, upload_to='productcategory/')),
                ('stockcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategories', to='inventory.stockcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='productcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='stockcategory',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to='stockcategory/'),
        ),
    ]
